baseURL = "https://luci.unimi.it/"
languageCode = "en-us"
title = "LUCI Lab"
enableRobotsTXT = true
paginate = 12
summaryLength = 30

[params]
  description = "Logic, Uncertainty, Computation and Information Lab — University of Milan"
  department = 'Department of Philosophy "Piero Martinetti"'
  university = "Università degli Studi di Milano"
  location = "Via Festa del Perdono, 7 — 20122 Milan"
  tagline = ""
  instagram = "https://www.instagram.com/logicgroupmilano/"
  linkedin = "https://www.linkedin.com/company/logic-uncertainty-computation-and-information-luci-lab/"
  youtube = "https://www.youtube.com/@lucigroup5155"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 1
[[menu.main]]
  name = "Members"
  url = "/members/"
  weight = 2
[[menu.main]]
  name = "Events"
  url = "/events/"
  weight = 3
[[menu.main]]
  name = "Seminars"
  url = "/seminars/"
  weight = 4
[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 5
[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 6
[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 7
[[menu.main]]
  name = "Open Positions"
  url = "/open-positions/"
  weight = 8
[[menu.main]]
  name = "Research Grants"
  url = "/grants/"
  weight = 9
